export const SCHIJF_VAN_VIJF = {
  // Peanut Butter
  "Calvé Pindakaas Original": false,
  "Skippy Creamy peanut butter": false,
  "Bonne Maman Pindapasta romig": false,
  "AH Biologisch Smeuïge pindakaas met stukjes pinda": false,
  "BioToday Peanutbutter crunchy bio": false,
  "Jumbo's 100% Natural Peanut Butter": true,
  "Whole earth Drizzler golden roasted peanut butter": true,
  "AH Terra Plantaardig biologisch 100% pindakaas": true,
  "Jumbo's 100% Biologische Pindakaas Naturel": true,
  "Luna E Terra Pindakaas Smooth Bio": true,
  // Pasta
  "De Cecco Penne Rigate Nr. 41": false,
  "La Molisana Penne rigate": false,
  "AH Biologisch Penne": false,
  "Grand' Italia Penne tradizionali": false,
  "La bioidea Penne": false,
  "Jumbo Penne Rigate Whole Wheat": true,
  "Jumbo Organic Whole Wheat Rigatoni": true,
  "Rummo Volkoren Biologische Penne Rigate": true,
  "Ekoplaza Volkoren penne": true,
  "AH Rode linzen penne": true,
  // Crackers
  "AH Biologisch Stevige crackers kaas": false,
  "AH Dunne crackers volkoren": false,
  "Jumbo Stevige Crackers Spelt 8": false,
  "Jumbo Groentecrackers Wortel & Zoete Aardappel": false,
  "Bolletje Oerknack Waldkorn": false,
  "AH Dunne crackers kaas": true,
  "AH Stevige crackers waldkorn": true,
  "Bolletje Low carb groentecrackers paprika": true,
  "Bolletje Ontbijt Crackers Spelt Volkoren": true,
  "TastyBasics Low carb-high protein cracker meerzaden": true,
  // Nuts
  "AH Cranberry notenmix ongezouten": false,
  "AH Terra Noten cranberry rozijn mix ongebrand": false,
  "Lidl cashew cranberrymix mix alesto": false,
  "Duyvis Oven baked peanuts honey salt": false,
  "Duyvis Oven roasted pinda's original": false,
  "Natural Happiness proteïnemix": true,
  "AH Terra Elitehaver ongebrand": true,
  "Alesto Noten mix": true,
  "Jumbo Studentenhaver Ongezouten": true,
  "Natural Happiness nut mix Raw": true,
  // Beans
  "Bonduelle Chilibonen in saus": false,
  "Hak witte bonen in tomatensaus": false,
  "Heinz Beanz": false,
  "Smaakt Bio Zwarte Bonen": false,
  "Hak Bonen Bruine": false,
  "Jumbo Hollandse Bruine Bonen": true,
  "Bonduelle Zwarte bonen": true,
  "Freshona Linzen Lentils lidl": true,
  "Hak Kapucijners": true,
  "AH Terra Jonge kapucijners": true,
  // Plant-based Drinks
  "AH Terra Plantaardige haverdrink ongezoet": false,
  "Alpro Haverdrink zonder suikers": false,
  "Jumbo Haverdrink Naturel": false,
  "Oatly! Organic oat drink": false,
  "Rude Health Barista soja": false,
  "AH Terra Plantaardige erwtendrink ongezoet": true,
  "Alpro Sojadrink Houdbaar": true,
  "Alpro Barista soja": true,
  "AH Terra Plantaardige sojadrink": true,
  "Jumbo Sojadrink Naturel": true,
  // Pasta Sauce
  "Spagheroni Tradizionale": false,
  "Heinz Traditional pasta sauce": false,
  "La Dolce Vita Traditional Pastasaus": false,
  "AH Biologisch Pastasaus tradizionale": false,
  "Fertilia Pastasaus traditionale": false,
  "Ecoplaza Pastasaus sugo tradizionale": false,
};

export const ALL_PRODUCTS = Object.keys(SCHIJF_VAN_VIJF).sort();
